const CIVIC_API_KEY = '';
const GOOGLE_CLIENT_ID = '';
const GOOGLE_CLIENT_SECRET = '';
const SESSION_SECRET = ''


exports.CIVIC_API_KEY = CIVIC_API_KEY;
exports.GOOGLE_CLIENT_ID = GOOGLE_CLIENT_ID;
exports.GOOGLE_CLIENT_SECRET = GOOGLE_CLIENT_SECRET;
exports.SESSION_SECRET = SESSION_SECRET;
