const TWILIO_ACCOUNT_SID = '';
const TWILIO_AUTH_TOKEN = '';
const TWILIO_TWIML_APP_SID = '';
const TWILIO_NUMBER = ''

module.exports.TWILIO_ACCOUNT_SID = TWILIO_ACCOUNT_SID;
module.exports.TWILIO_AUTH_TOKEN = TWILIO_AUTH_TOKEN;
module.exports.TWILIO_TWIML_APP_SID = TWILIO_TWIML_APP_SID;
module.exports.TWILIO_NUMBER = TWILIO_NUMBER;